services:
  # PostgreSQLデータベース
  db:
    image: postgres:15
    container_name: bento_db
    environment:
      POSTGRES_DB: bento_ordering
      POSTGRES_USER: bento_user
      POSTGRES_PASSWORD: bento_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bento_network

  # FastAPIアプリケーション
  web:
    build: .
    container_name: bento_web
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./templates:/app/templates
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    environment:
      - DATABASE_URL=postgresql+asyncpg://bento_user:bento_password@db:5432/bento_ordering
      - SECRET_KEY=your-secret-key-change-this-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db
    networks:
      - bento_network
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        sleep 10 &&
        echo 'Running database migrations...' &&
        alembic upgrade head &&
        echo 'Starting application...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  # pgAdmin（開発用データベース管理ツール）
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bento_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - bento_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  bento_network:
    driver: bridge